/// <reference types="vite/client" />
/// <reference types="react-router" />
/// <reference path="./worker-configuration.d.ts" />

// Enhance TypeScript's built-in typings.
import '@total-typescript/ts-reset';

import type {
  HydrogenContext,
  HydrogenSessionData,
  HydrogenEnv,
} from '@shopify/hydrogen';
import type {createAppLoadContext} from '~/lib/context';

declare global {
  /**
   * A global `process` object is available during build and runtime.
   */
  const process: {env: NodeJS.ProcessEnv};

  interface Env extends HydrogenEnv, Cloudflare.Env {
    // Additional environment variables beyond what's auto-generated by Wrangler
    // Note: Most env vars are now auto-generated in worker-configuration.d.ts
    // Only add custom ones here if needed
  }
}

declare module 'react-router' {
  interface AppLoadContext
    extends Awaited<ReturnType<typeof createAppLoadContext>> {
    // to change context type, change the return of createAppLoadContext() instead
  }

  // TODO: remove this once we've migrated our loaders to `Route.LoaderArgs`
  interface LoaderFunctionArgs {
    context: AppLoadContext;
  }

  // TODO: remove this once we've migrated our loaders to `Route.ActionArgs`
  interface ActionFunctionArgs {
    context: AppLoadContext;
  }

  interface SessionData extends HydrogenSessionData {
    // declare local additions to the Remix session data here
  }
}

declare namespace NodeJS {
  interface ProcessEnv {
    NODE_ENV: 'development' | 'production';
    // Note: Other environment variables are now auto-generated in worker-configuration.d.ts
    // Add Node.js-specific environment variables here if needed
  }
}
